core/urls.py
from django.contrib import admin
from django.urls import path,include,reverse
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('admin/', admin.site.urls),
    path('', include('product.urls')),
    path('user/', include('user.urls')),
    path('dj-rest-auth/', include('dj_rest_auth.urls'), name='rest_auth'),
    path('dj-rest-auth/registration/', include('dj_rest_auth.registration.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from .views.category import ListCreateView
from .views.product import ProductListCreateView, ProductListView,ProductRetrieveUpdateDestroyView

app_name = 'product'
urlpatterns = [
    path('', ListCreateView.as_view(), name = 'categorys'),
    path('category/product/<int:pk>/', ProductListCreateView.as_view(), name='category_by_product'),
    path('products/', ProductListView.as_view(), name='products'),
    path('procuct/<int:pk>/', ProductRetrieveUpdateDestroyView.as_view(), name='product'),
]

product/models.py
from django.db import models

class Category(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField()
    img = models.ImageField(upload_to='category_imgs')
    created = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updeted = models.DateTimeField(auto_now=True, blank=True, null=True)
    
    class Meta:
        ordering = ['-id']

    def __str__(self) -> str:
        return self.title
    
class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    
    title = models.CharField(max_length=120)
    description = models.TextField()
    img = models.ImageField(upload_to='product_imgs')
    quantity = models.PositiveIntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updeted = models.DateTimeField(auto_now=True, blank=True, null=True)

    class Meta:
        ordering = ['-id']

    def __str__(self) -> str:
        return self.title
    

product/views/category.py
from rest_framework import generics
from rest_framework.response import Response
from ..serializers import Category, CategorySerializer
from ..serializers import Product, ProductSerializer
from django.shortcuts import render

class ListCreateView(generics.ListCreateAPIView):
    queryset = CategorySerializer
    serializer_class = Category.objects.all()

    def list(self, request):
        category_bojs = Category.objects.all()
        categorys = CategorySerializer(category_bojs, many = True)

        product_objs = Product.objects.all()
        product = ProductSerializer(product_objs, many = True)

        data_boj = Category.objects.first()
        data = CategorySerializer(data_boj).data

        return render(
            request=request,
            template_name='home.html', 
            context={'category':categorys.data, 'product':product.data, 'data':data}
            )

product/views/product.py
from rest_framework import generics
from rest_framework.response import Response
from ..serializers import Category, CategorySerializer
from ..serializers import Product, ProductSerializer
from rest_framework.permissions import IsAdminUser, IsAuthenticatedOrReadOnly
from django.shortcuts import render
from rest_framework import filters


class ProductRetrieveUpdateDestroyView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [filters.SearchFilter]
    search_fields = ['title', 'description']

class ProductListCreateView(generics.ListCreateAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer

    def list(self, request, pk:int):
        product_objs = Product.objects.filter(category = pk)
        product = ProductSerializer(product_objs, many = True)

        category_objs = Category.objects.all()
        categorys = CategorySerializer(category_objs, many = True)

        data_obj = Category.objects.get(id = pk)
        data = CategorySerializer(data_obj, many = False)

        return render(
            request=request, 
            template_name='category.html', 
            context={'product':product.data, 'category':categorys.data, 'data':data.data}
            )
    
class ProductListView(generics.ListAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    permission_classes = [IsAdminUser | IsAuthenticatedOrReadOnly]
    filter_backends = [filters.SearchFilter]
    search_fields = ['title', 'description']

    def list(self, request):
        product_objs = Product.objects.all()
        product = ProductSerializer(product_objs, many = True)

        category_objs = Category.objects.all()
        categorys = CategorySerializer(category_objs, many = True)
        return render(
            request=request, 
            template_name='products.html', 
            context={'product':product.data, 'category':categorys.data}
            )
    
class ProductRetrieveUpdateDestroyView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer()
    permission_classes = [IsAdminUser | IsAuthenticatedOrReadOnly]
    filter_backends = [filters.SearchFilter]
    search_fields = ['title', 'description']

    def retrieve(self, request, *args, **kwargs):
        product_obj = Product.objects.get(id = kwargs['pk'])
        product = ProductSerializer(product_obj, many = False)

        product_objs = Product.objects.filter(category = product_obj.category)
        products = ProductSerializer(product_objs, many = True)

        category_objs = Category.objects.all()
        categorys = CategorySerializer(category_objs, many = True)

        return render(
            request=request,
            template_name='product.html',
            context={
                'product':product.data,
                'products':products.data,
                'category':categorys.data,
            }
            )

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>{% block title %} {% endblock %}</title>
    <style>
      .bi-heart:hover{
        width: 30px;
        height: 30px;
        margin-left: 17px;
      }
      .bi-heart{
        margin-left: 20px;
      }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'product:categorys' %}">Smart shop</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'product:categorys' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'product:products' %}">Products</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Category
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% for i in category %}
                        <li><a class="dropdown-item" href="{% url 'product:category_by_product' i.id %}">{{ i.title }}</a></li>
                    {% endfor %}
                </ul>
              </li>
            </ul>
            <form class="d-flex">
              <input class="form-control me-5" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success me-5" type="submit">Search</button>
              {% if request.user.is_authenticated %}
              <div class="collapse navbar-collapse me-5" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="d-flex nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      {{ request.user.username }}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">

                      <!-- login -->
                      <form action="http://127.0.0.1:8000/dj-rest-auth/logout/" method="get">
                        {% csrf_token %}
                        <li><button type="submit" class="dropdown-item">Logout</button></li>
                      </form>

                      <li><a class="dropdown-item" href="#">My accout</a></li>
                      {% if request.user.is_staff %}
                        {% comment %} <li><a class="dropdown-item" href="{% url 'user:adminview' %}">Admin view</a></li> {% endcomment %}
                      {% endif %}
                    </ul>
                  </li>
                </ul>
              </div>
            {% else %}
            <div class="collapse navbar-collapse me-5" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="d-flex nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    None user
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">

                     <!-- login -->
                     <form action="http://127.0.0.1:8000/dj-rest-auth/login/" method="post">
                      {% csrf_token %}
                      <li><button type="submit" class="dropdown-item">Logout</button></li>
                    </form>
                    
                    <!-- logout -->
                    <form action="http://127.0.0.1:8000/dj-rest-auth/logout/" method="post">
                      {% csrf_token %}
                      <li><button type="submit" class="dropdown-item">Logout</button></li>
                    </form>

                    <li><a class="dropdown-item" href="#">Register</a></li>
                  </ul>
                </li>
              </ul>
            </div>
            {% endif %}
            </form>
          </div>
        </div>
    </nav>
        
    {% block content %}

    {% endblock %}
</body>
</html>

templates/category.html
{% extends "base.html" %}

{% block title %}{{ product.category }}{% endblock %}

{% block content %}
    <center>
        <div class="card mb-3 mt-1" style="width: 100%; height: 100%;">
            <div class="row g-0">
            <div class="col-md-6">
                <img src="http://127.0.0.1:8000{{data.img}}" style="height: 100%; width: 100%;" class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-5">
                <div class="card-body">
                <h3 class="card-title">{{data.title}}</h3>
                <p class="card-text">{{data.description}}</p>
                <p class="card-text"><small class="text-muted">Created {{ data.created }} ago</small></p>
                <p class="card-text"><small class="text-muted">Last updated {{ data.updeted }} ago</small></p>
                </div>
            </div>
            </div>
        </div>
    </center>
    <h1>Category is {{data.title}}</h1>
    <hr class="dropdown-divider">
    
    <div class="container card-group mt-5">
        
        {% for i in product %}
                <div class="me-5 mb-5" style="width: 18rem;">
                    <img src="http://127.0.0.1:8000{{ i.img }}" class="card-img-top" alt="...">
                    <div class="card-body">
                    <h5 class="card-title">{{ i.title }}</h5>
                    <p class="card-text">{{ i.description }}</p>
                {% if i.quantity %}
                    <p class="card-text text-success">We have {{ i.quantity }} this products now</p>
                    <a href="#" class="btn btn-primary">add card</a>
                {% else %}
                    <p class="card-text text-danger">We don't have this product now</p>
                    <a href="#" class="btn btn-primary disabled">add card</a>
                {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
    
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block title %}home{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                <center>
                    <div class="carousel-inner" style="height: auto;">
                        {% for i in category %}
                            {% if i.img == data.img %}
                                <div class="carousel-item active">
                                    <img src="{{ i.img }}" class="d-block w-100" style="height: 500px;" alt="...">
                                    <div class="carousel-caption d-none d-md-block">
                                        <a href="{% url 'product:category_by_product' i.id %}" style="color: white; font-family: 'Courier New', Courier, monospace;">
                                            <h5>{{ i.title }}</h5>
                                            <p>{{ i.description }}</p>
                                        </a>
                                      </div>
                                </div>
                            {% else %}
                                <div class="carousel-item">
                                    <img src="{{ i.img }}" class="d-block w-100" style="height: 500px; font-family: 'Courier New', Courier, monospace;" alt="...">
                                    <div class="carousel-caption d-none d-md-block">
                                        <a href="{% url 'product:category_by_product' i.id %}" style="color: white;">
                                            <h5>{{ i.title }}</h5>
                                            <p>{{ i.description }}</p>
                                        </a>
                                      </div>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </center>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
    </div>

    <h1>Home</h1>
    <hr class="dropdown-divider">
    
    <div class="container card-group mt-5">
        
        {% for i in product %}
                <div class="me-5 mb-5" style="width: 18rem;">
                    <img src="http://127.0.0.1:8000{{ i.img }}" class="card-img-top" alt="...">
                    <div class="card-body">
                    <h5 class="card-title">{{ i.title }}</h5>
                    <p class="card-text">{{ i.description }}</p>
                {% if i.quantity %}
                    <p class="card-text text-success">We have {{ i.quantity }} this products now</p>
                    <a href="{% url 'product:product' i.id %}" class="btn btn-primary">add card</a>
                {% else %}
                    <p class="card-text text-danger">We don't have this product now</p>
                    <a href="{% url 'product:product' i.id %}" class="btn btn-primary disabled">add card</a>
                {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
    
{% endblock %}

templates/product.html
{% extends "base.html" %}

{% block title %}{{ product.title }}{% endblock %}

{% block content %}
        <div class="card mb-3 mt-1" style="width: 100%; height: 100%;">
            <div class="row g-0">
                <div class="col-md-4 col-md-6">
                    <img src="http://127.0.0.1:8000{{ product.img }}" style="height: 100%; width: 100%;" class="img-fluid rounded-start" alt="...">
                </div>
                <div class="col-md-6">
                    <div class="card-body">
                    <h5 class="card-title">{{ product.title }}</h5>
                    <p class="card-text">{{ product.description }}</p>
                        <p class="card-text text-success">We have {{ product.quantity }} this products now</p>
                    <p class="card-text"><small class="text-muted">Created {{ product.created }} ago</small></p>
                    <p class="card-text"><small class="text-muted">Last updated {{ product.updeted }} ago</small></p>
                    <a href="#" class="btn btn-success" role="button" aria-pressed="true">add card</a>
                    <!-- <a href="#" class="btn btn-outline-danger" role="button" aria-pressed="true">Line</a> -->
                    <a href="#">
                        <svg xmlns="http://www.w3.org/2000/svg" width="27" height="27" fill="currentColor" class="bi bi-heart" style="color: red;" viewBox="0 0 16 16">
                            <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
                        </svg>
                    </a>
                </div>
                </div>
            </div>
    <h1>Product</h1>
    <hr class="dropdown-divider">
    
    <div class="container card-group mt-5">
        
        {% for i in products %}
                <div class="me-5 mb-5" style="width: 18rem;">
                    <img src="http://127.0.0.1:8000{{ i.img }}" class="card-img-top" alt="...">
                    <div class="card-body">
                    <h5 class="card-title">{{ i.title }}</h5>
                    <p class="card-text">{{ i.description }}</p>
                {% if i.quantity %}
                    <p class="card-text text-success">We have {{ i.quantity }} this products now</p>
                    <a href="{% url 'product:product' i.id %}" class="btn btn-primary">add card</a>
                {% else %}
                    <p class="card-text text-danger">We don't have this product now</p>
                    <a href="{% url 'product:product' i.id %}" class="btn btn-primary disabled">add card</a>
                {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
    
{% endblock %}

templates/products.html
{% extends "base.html" %}

{% block title %}{{ product.category }}{% endblock %}

{% block content %}
    <h1>Products</h1>
    <hr class="dropdown-divider">
    
    <div class="container card-group mt-5">
        
        {% for i in product %}
                <div class="me-5 mb-5" style="width: 18rem;">
                    <img src="http://127.0.0.1:8000{{ i.img }}" class="card-img-top" alt="...">
                    <div class="card-body">
                    <h5 class="card-title">{{ i.title }}</h5>
                    <p class="card-text">{{ i.description }}</p>
                {% if i.quantity %}
                    <p class="card-text text-success">We have {{ i.quantity }} this products now</p>
                    <a href="{% url 'product:product' i.id %}" class="btn btn-primary">add card</a>
                {% else %}
                    <p class="card-text text-danger">We don't have this product now</p>
                    <a href="{% url 'product:product' i.id %}" class="btn btn-primary disabled">add card</a>
                {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
    
{% endblock %}